"""Background implications between one-variable magma laws, derived syntactically.

An implication P -> C between laws holds in every magma when each law of C can
be derived from the laws of P with the rules of equational logic. Three rules
are used here:

1. multiply both sides of an equation by the same term from the same side,
   s = t  |-  u * s = u * t  and  s * u = t * u;
2. replace all occurrences of the variable by the same term,
   s = t  |-  s[x := u] = t[x := u];
3. replace one occurrence of a subterm by an equivalent one,
   a = b, e  |-  e[a := b]  (one occurrence, either way round),
   which covers symmetry and transitivity: rewriting the side a of a = c
   by a = b gives b = c.

Rules 1 and 2 only make equations bigger, so derivations are bounded by an
order: every equation they pass through, the premises and the conclusion
included, has at most `order` binary operations in its two sides together.
A larger order finds more implications, at a cost that grows quickly with it.

Only laws in a single variable are supported: with more variables, rule 2
would have to rename variables apart and identify laws up to renaming.
"""

from __future__ import annotations

from collections.abc import Iterable, Iterator, Sequence
from itertools import combinations

from conceptual_exploration.algorithms.next_closure import NextClosure
from conceptual_exploration.core.bitset import AttributeIndex
from conceptual_exploration.core.implication import Implication
from conceptual_exploration.core.theory import ImplicationTheory
from explorations.equational_theories.magma import ETP, Equation, Op, Term, Var

class Derivations:
    """Derives one-variable laws with the three rules within an order bound.

    Every term that can occur, one with at most `order` operations, is
    numbered once, and so is every non-trivial equation between them: a pair
    of term numbers, smaller first, so that the two ways of writing a law
    coincide. The rules are then instantiated once and for all, each instance
    an implication from one or two equations to a third, and `closure` is
    forward chaining over those implications. Applying the rules anew for
    every closure would repeat the same work each time.
    """

    def __init__(self, variable: str, order: int) -> None:
        if order < 0:
            raise ValueError(f"order must be non-negative, got {order}")
        self.variable = variable
        self.order = order
        # Generated by operation count, so the factors of a term come first.
        self.terms: list[Term] = ETP.generate_terms([variable], order)
        self.ids: dict[Term, int] = {term: i for i, term in enumerate(self.terms)}
        self._ops = [term.op_count() for term in self.terms]
        self._factors: list[tuple[int, int] | None] = []
        self._products: dict[tuple[int, int], int] = {}
        self._subterms: list[frozenset[int]] = []
        for i, term in enumerate(self.terms):
            if isinstance(term, Op):
                left, right = self.ids[term.left], self.ids[term.right]
                self._factors.append((left, right))
                self._products[(left, right)] = i
                self._subterms.append(self._subterms[left] | self._subterms[right] | {i})
            else:
                self._factors.append(None)
                self._subterms.append(frozenset([i]))
        self._variable = self.ids[Var(variable)]
        self._substitutions: dict[tuple[int, int], int | None] = {}

        ops = self._ops
        self.equations: list[tuple[int, int]] = [
            (a, b)
            for a in range(len(self.terms))
            for b in range(a + 1, len(self.terms))
            if ops[a] + ops[b] <= order
        ]
        self._numbers = {equation: i for i, equation in enumerate(self.equations)}
        # The instances of the rules: for each equation, what it derives
        # alone, and the two-premise instances it takes part in, numbered,
        # with the conclusion of each.
        self._derives: list[set[int]] = [set() for _ in self.equations]
        self._takes_part: list[list[int]] = [[] for _ in self.equations]
        self._conclusions: list[int] = []
        self._instantiate()

    def pair(self, lhs: Term, rhs: Term) -> tuple[int, int]:
        """The numbered form of the equation lhs = rhs."""
        a, b = self.ids[lhs], self.ids[rhs]
        return (a, b) if a <= b else (b, a)

    def _number(self, a: int | None, b: int | None) -> int | None:
        """The number of the equation a = b, or None if it is trivial or has
        more than `order` operations."""
        if a is None or b is None or a == b or self._ops[a] + self._ops[b] > self.order:
            return None
        return self._numbers[(a, b) if a < b else (b, a)]

    def _instantiate(self) -> None:
        ops, products = self._ops, self._products
        pairs: set[tuple[int, int, int]] = set()
        # The equations by the subterms they contain, for rule 3.
        containing: dict[int, list[int]] = {}
        for i, (s, t) in enumerate(self.equations):
            for term in self._subterms[s] | self._subterms[t]:
                containing.setdefault(term, []).append(i)

        for i, (s, t) in enumerate(self.equations):
            size = ops[s] + ops[t]
            derived = []
            for u in range(len(self.terms)):
                # Rule 1: u * s = u * t and s * u = t * u.
                if size + 2 * (ops[u] + 1) <= self.order:
                    derived.append(self._number(products.get((u, s)), products.get((u, t))))
                    derived.append(self._number(products.get((s, u)), products.get((t, u))))
                # Rule 2: s[x := u] = t[x := u]. With one variable a side of
                # n operations has n + 1 occurrences of it.
                if u != self._variable and size + (size + 2) * ops[u] <= self.order:
                    derived.append(self._number(self._substitute(s, u), self._substitute(t, u)))
            # Rule 3: equation i rewrites one occurrence of a side in an
            # equation containing it, itself included.
            for old, new in ((s, t), (t, s)):
                for j in containing.get(old, ()):
                    lhs, rhs = self.equations[j]
                    conclusions = [
                        self._number(replaced, rhs) for replaced in self._replace_one(lhs, old, new)
                    ] + [
                        self._number(lhs, replaced) for replaced in self._replace_one(rhs, old, new)
                    ]
                    for c in conclusions:
                        if c is None or c in (i, j):
                            continue
                        if i == j:
                            derived.append(c)
                        else:
                            pairs.add((min(i, j), max(i, j), c))
            self._derives[i].update(c for c in derived if c is not None and c != i)

        for i, j, c in sorted(pairs):
            k = len(self._conclusions)
            self._conclusions.append(c)
            self._takes_part[i].append(k)
            self._takes_part[j].append(k)

    def closure(self, seeds: Iterable[tuple[int, int]]) -> set[tuple[int, int]]:
        """Every non-trivial equation of order at most `order` that the seeds
        derive along derivations staying within that order, the seeds
        included. Trivial seeds derive nothing and are left out.

        A two-premise instance fires once both of its premises are derived,
        which a count per instance tells; every equation is handled once.
        """
        derived = {self._numbers[(a, b)] for a, b in seeds if a != b}
        stack = list(derived)
        halves: set[int] = set()
        while stack:
            i = stack.pop()
            for c in self._derives[i]:
                if c not in derived:
                    derived.add(c)
                    stack.append(c)
            for k in self._takes_part[i]:
                if k not in halves:
                    halves.add(k)
                    continue
                c = self._conclusions[k]
                if c not in derived:
                    derived.add(c)
                    stack.append(c)
        return {self.equations[i] for i in derived}

    def _replace_one(self, term: int, old: int, new: int) -> list[int]:
        """Every term obtained from `term` by replacing one occurrence of
        `old` by `new`, leaving out those with more than `order` operations."""
        if term == old:
            return [new]
        if old not in self._subterms[term]:
            return []
        left, right = self._factors[term]
        result = []
        for replaced in self._replace_one(left, old, new):
            product = self._products.get((replaced, right))
            if product is not None:
                result.append(product)
        for replaced in self._replace_one(right, old, new):
            product = self._products.get((left, replaced))
            if product is not None:
                result.append(product)
        return result

    def _substitute(self, term: int, u: int) -> int | None:
        """`term` with the variable replaced by `u`, or None if that has more
        than `order` operations."""
        key = (term, u)
        if key not in self._substitutions:
            factors = self._factors[term]
            if factors is None:
                result = u
            else:
                left = self._substitute(factors[0], u)
                right = self._substitute(factors[1], u)
                result = None if left is None or right is None else self._products.get((left, right))
            self._substitutions[key] = result
        return self._substitutions[key]


def background_implications(
        equations: Sequence[Equation],
        order: int,
        max_premise_size: int | None = 2,
) -> list[Implication[Equation]]:
    """Implications between `equations` derivable with the three rules along
    derivations of at most `order` operations.

    With `max_premise_size` None, the result is the canonical basis of the
    derivable implications, computed with NextClosure over the equations. Its
    premises are the pseudo-closed sets, of any size, and enumerating them
    visits every set closed under derivation, which with a small order may be
    nearly all of them. A number instead bounds the premises: every set of at
    most that many equations implies what it derives, unless the
    implications kept so far already entail that. The result is then sound
    but may miss implications whose premises are larger.

    A trivial equation (x = x) is derivable from nothing, and is the
    conclusion of an implication with an empty premise.
    """
    variables = set().union(*(eq.variables for eq in equations))
    if len(variables) > 1:
        raise ValueError(
            f"Background implications need laws in one variable, got {sorted(variables)}"
        )
    too_big = [eq for eq in equations if eq.lhs.op_count() + eq.rhs.op_count() > order]
    if too_big:
        raise ValueError(f"order {order} is below the order of {too_big[0]}")

    derivations = Derivations(next(iter(variables), "x"), order)
    pairs = [derivations.pair(eq.lhs, eq.rhs) for eq in equations]
    # The equations by their numbered form: a law may be listed twice.
    trivial = 0
    by_pair: dict[tuple[int, int], int] = {}
    for i, (lhs, rhs) in enumerate(pairs):
        if lhs == rhs:
            trivial |= 1 << i
        else:
            by_pair[(lhs, rhs)] = by_pair.get((lhs, rhs), 0) | 1 << i

    def closure_mask(mask: int) -> int:
        seeds = [pairs[i] for i in range(len(pairs)) if mask >> i & 1]
        result = mask | trivial
        for pair in derivations.closure(seeds):
            result |= by_pair.get(pair, 0)
        return result

    index = AttributeIndex[Equation](equations)
    theory = ImplicationTheory[Equation](index=index)

    def accept(premise: int, closure: int) -> None:
        theory.add(Implication(index.decode(premise), index.decode(closure & ~premise)))

    if max_premise_size is None:
        premises = NextClosure(equations, mask_closure_operator=theory.closure_mask).generate_masks()
        try:
            premise = next(premises)
            while True:
                closure = closure_mask(premise)
                if closure != premise:
                    accept(premise, closure)
                    premise = premises.send(True)
                else:
                    premise = next(premises)
        except StopIteration:
            pass
        return list(theory)

    if trivial:
        accept(0, trivial)
    for premise in _masks_up_to(len(equations), max_premise_size):
        if premise & trivial:
            continue
        closure = closure_mask(premise)
        if not theory.entails_mask(premise, closure):
            accept(premise, closure)
    return list(theory)


def _masks_up_to(n: int, size: int) -> Iterator[int]:
    """The non-empty subsets of n positions with at most `size` elements, as
    masks, smaller subsets first."""
    for k in range(1, min(size, n) + 1):
        for positions in combinations(range(n), k):
            mask = 0
            for i in positions:
                mask |= 1 << i
            yield mask
