"""Sudoku exploration domain.

Provides SAT-based (PySAT) and SMT-based (Z3) representations of Sudoku puzzles,
automated counterexample generation, symmetry transformations, and first-order
relational predicates for conceptual exploration.
"""

from .sudoku import (
    CELL_EQUIVALENCES,
    COMPLETION_PREDICATES,
    GEOMETRIC_PREDICATES,
    PREDICATE_PROPERTIES,
    PREDICATE_SORTS,
    PRIMITIVE_PREDICATES,
    CegarPartialGridExpert,
    PartialGridExpert,
    SatSudokuRuleExpert,
    SudokuExpert,
    SudokuRuleWitness,
    SudokuSort,
    Z3SudokuExpert,
    assemble_solution,
    block_cells,
    check_rule_exploration,
    check_rules,
    confinement_cells,
    cell_exploration,
    cell_number_exploration,
    column_cells,
    geometry_basis,
    get_coords,
    get_sudoku_attributes,
    get_sudoku_background_implications,
    get_sudoku_predicates,
    get_sudoku_symmetries,
    get_var,
    make_number_mapping,
    print_solution,
    row_cells,
    run_sudoku_rule_exploration,
    run_sudoku_sat_exploration,
    select_predicates,
    solve_sudoku,
    sudoku2sat,
    sudoku_background,
    sudoku_predicates,
    sudoku_rule_exploration,
    sudoku_solutions,
    z3_same_block,
    z3_same_block_coords,
    z3_together,
    z3_variables,
    z3predicates,
)

from .config import (
    CONFIG_DIR,
    ExplorationConfig,
    available_configs,
    load_config,
    partial_grid_exploration,
)

__all__ = [
    "CONFIG_DIR",
    "ExplorationConfig",
    "available_configs",
    "load_config",
    "CELL_EQUIVALENCES",
    "COMPLETION_PREDICATES",
    "GEOMETRIC_PREDICATES",
    "PREDICATE_PROPERTIES",
    "PREDICATE_SORTS",
    "PRIMITIVE_PREDICATES",
    "CegarPartialGridExpert",
    "PartialGridExpert",
    "SatSudokuRuleExpert",
    "SudokuExpert",
    "SudokuRuleWitness",
    "SudokuSort",
    "Z3SudokuExpert",
    "assemble_solution",
    "block_cells",
    "check_rule_exploration",
    "check_rules",
    "confinement_cells",
    "cell_exploration",
    "cell_number_exploration",
    "column_cells",
    "geometry_basis",
    "get_coords",
    "get_sudoku_attributes",
    "get_sudoku_background_implications",
    "get_sudoku_predicates",
    "get_sudoku_symmetries",
    "get_var",
    "make_number_mapping",
    "partial_grid_exploration",
    "print_solution",
    "row_cells",
    "run_sudoku_rule_exploration",
    "run_sudoku_sat_exploration",
    "select_predicates",
    "solve_sudoku",
    "sudoku2sat",
    "sudoku_background",
    "sudoku_predicates",
    "sudoku_rule_exploration",
    "sudoku_solutions",
    "z3_same_block",
    "z3_same_block_coords",
    "z3_together",
    "z3_variables",
    "z3predicates",
]
