"""Sudoku exploration domain.

Provides SAT-based (PySAT) and SMT-based (Z3) representations of Sudoku puzzles,
automated counterexample generation, symmetry transformations, and first-order
relational predicates for conceptual exploration.
"""

from .sudoku import (
    CELL_EQUIVALENCES,
    PRIMITIVE_PREDICATES,
    SudokuExpert,
    SudokuSort,
    Z3SudokuExpert,
    assemble_solution,
    block_cells,
    cell_exploration,
    cell_number_exploration,
    column_cells,
    get_coords,
    get_sudoku_attributes,
    get_sudoku_background_implications,
    get_sudoku_predicates,
    get_sudoku_symmetries,
    get_var,
    make_number_mapping,
    print_solution,
    row_cells,
    run_sudoku_rule_exploration,
    run_sudoku_sat_exploration,
    select_predicates,
    solve_sudoku,
    sudoku2sat,
    sudoku_background,
    z3_same_block,
    z3_same_block_coords,
    z3_together,
    z3_variables,
    z3predicates,
)

__all__ = [
    "CELL_EQUIVALENCES",
    "PRIMITIVE_PREDICATES",
    "SudokuExpert",
    "SudokuSort",
    "Z3SudokuExpert",
    "assemble_solution",
    "block_cells",
    "cell_exploration",
    "cell_number_exploration",
    "column_cells",
    "get_coords",
    "get_sudoku_attributes",
    "get_sudoku_background_implications",
    "get_sudoku_predicates",
    "get_sudoku_symmetries",
    "get_var",
    "make_number_mapping",
    "print_solution",
    "row_cells",
    "run_sudoku_rule_exploration",
    "run_sudoku_sat_exploration",
    "select_predicates",
    "solve_sudoku",
    "sudoku2sat",
    "sudoku_background",
    "z3_same_block",
    "z3_same_block_coords",
    "z3_together",
    "z3_variables",
    "z3predicates",
]
